export const InterviewConstant = {
    ALL_QUESTION_DATA: "ALL_QUESTION_DATA",
    ALL_CANDIDATE_DATA: "ALL_CANDIDATE_DATA",
    ALL_HR_DOCUMENT_DATA: "ALL_HR_DOCUMENT_DATA",
    ALL_CANDIDATE_ACCESS: "ALL_CANDIDATE_ACCESS",
    ALL_HR_DOCUMENT_DATA_BY_ID: "ALL_HR_DOCUMENT_DATA_BY_ID",
    ALL_PHOTO_DATA : "ALL_PHOTO_DATA",
    ALL_REQUIREMENT_DATA : "ALL_REQUIREMENT_DATA",
    ALL_USER_DATA : "ALL_USER_DATA",
  };
  