export const InterviewConstant = {
    ALL_QUESTION_DATA: "ALL_QUESTION_DATA",
    ALL_CANDIDATE_DATA: "ALL_CANDIDATE_DATA",
    ALL_HR_DOCUMENT_DATA: "ALL_HR_DOCUMENT_DATA",
    ALL_CANDIDATE_ACCESS: "ALL_CANDIDATE_ACCESS",
  };
  